# Generated by Django 4.0.3 on 2022-04-06 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variantoption',
            name='image',
        ),
    ]
