# Generated by Django 4.0.3 on 2022-04-06 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_orderproduct_product_variant_orderproduct_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.variantoption'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.variantoption'),
        ),
    ]
